import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#061225",
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingTop: 26,
    paddingBottom: 46,
  },

  heroSection: {
    minHeight: 265,
    backgroundColor: "#071B36",
    borderRadius: 32,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 42,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    marginBottom: -18,
  },
  heroGlowOne: {
    position: "absolute",
    top: -90,
    right: -80,
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: "rgba(37, 99, 235, 0.42)",
  },
  heroGlowTwo: {
    position: "absolute",
    bottom: -95,
    left: -90,
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: "rgba(14, 165, 233, 0.24)",
  },
  logoBox: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    shadowColor: "#2563EB",
    shadowOffset: {
      width: 0,
      height: 14,
    },
    shadowOpacity: 0.34,
    shadowRadius: 24,
    elevation: 8,
  },
  appName: {
    color: "#93C5FD",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.4,
    textTransform: "uppercase",
    marginBottom: 8,
    textAlign: "center",
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: -0.8,
    lineHeight: 31,
    textAlign: "center",
  },
  heroSubtitle: {
    color: "#B6C7DD",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 8,
    maxWidth: 290,
    textAlign: "center",
  },
  securityRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 16,
    marginBottom: 4,
  },
  securityChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.10)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    marginHorizontal: 4,
    marginBottom: 8,
  },
  securityChipText: {
    color: "#E5F0FF",
    fontSize: 11,
    fontWeight: "800",
    marginLeft: 6,
  },

  loginSheet: {
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 22,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 18,
    },
    shadowOpacity: 0.22,
    shadowRadius: 30,
    elevation: 10,
  },
  sheetHandle: {
    width: 44,
    height: 5,
    borderRadius: 99,
    backgroundColor: "#CBD5E1",
    alignSelf: "center",
    marginBottom: 18,
  },
  cardTitle: {
    color: "#0F172A",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.45,
    textAlign: "center",
  },
  cardDescription: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 20,
    marginTop: 8,
    marginBottom: 18,
    textAlign: "center",
  },
  label: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "900",
    marginBottom: 8,
    marginTop: 6,
  },
  input: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 14,
    color: "#0F172A",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 13,
  },
  passwordInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#CBD5E1",
    borderRadius: 15,
    marginBottom: 13,
  },
  passwordInput: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 8,
    paddingVertical: 14,
    color: "#0F172A",
    fontSize: 14,
    fontWeight: "600",
  },
  eyeButton: {
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  errorBox: {
    backgroundColor: "#FEF2F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: 13,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 2,
    marginBottom: 13,
  },
  errorText: {
    color: "#B91C1C",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  button: {
    backgroundColor: "#2563EB",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    marginTop: 4,
    shadowColor: "#2563EB",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 5,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "900",
  },
  infoStrip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 14,
  },
  infoStripText: {
    color: "#1E3A8A",
    fontSize: 11,
    fontWeight: "800",
    marginLeft: 7,
    textAlign: "center",
  },

  apiDebugBox: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 12,
  },
  apiDebugLabel: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  apiDebugValue: {
    color: "#0F172A",
    fontSize: 11,
    fontWeight: "800",
  },

  footer: {
    marginTop: 20,
    alignItems: "center",
  },
  footerText: {
    color: "#B6C7DD",
    fontSize: 11,
    fontWeight: "900",
  },
  footerSubText: {
    color: "#7F93AD",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 5,
    textAlign: "center",
  },
});