import { StyleSheet } from "react-native";

const ui = {
  background: "#F3F4F8",
  card: "#FFFFFF",
  text: "#111827",
  textSoft: "#64748B",
  muted: "#94A3B8",
  border: "#E2E8F0",
  blue: "#2563EB",
  cyan: "#0891B2",
  navy: "#07111F",
  shadow: "#64748B",
};

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: ui.background,
  },
  safeTopBlock: {
    backgroundColor: ui.background,
  },
  scrollArea: {
    flex: 1,
    backgroundColor: ui.background,
  },
  container: {
    paddingHorizontal: 18,
  },

  pageHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  pageTitle: {
    color: ui.text,
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.8,
  },
  pageMeta: {
    color: ui.textSoft,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 6,
  },
  refreshButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    backgroundColor: ui.card,
    borderWidth: 1,
    borderColor: ui.border,
    alignItems: "center",
    justifyContent: "center",
  },

  heroCard: {
    backgroundColor: "#07111F",
    borderRadius: 28,
    padding: 20,
    marginBottom: 18,
    overflow: "hidden",
  },
  heroGlowTop: {
    position: "absolute",
    width: 190,
    height: 190,
    borderRadius: 190,
    backgroundColor: "rgba(37, 99, 235, 0.45)",
    top: -78,
    right: -68,
  },
  heroGlowBottom: {
    position: "absolute",
    width: 160,
    height: 160,
    borderRadius: 160,
    backgroundColor: "rgba(8, 145, 178, 0.28)",
    bottom: -85,
    left: -70,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  heroIcon: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: ui.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  heroBadge: {
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  heroBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.55,
    marginTop: 28,
  },
  heroDesc: {
    color: "#B6C7DD",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 20,
    marginTop: 10,
  },
  heroDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.16)",
    marginTop: 24,
    marginBottom: 18,
  },
  heroStats: {
    flexDirection: "row",
    alignItems: "center",
  },
  heroStatItem: {
    flex: 1,
  },
  heroStatValue: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.7,
  },
  heroStatLabel: {
    color: "#8EA4BE",
    fontSize: 10,
    fontWeight: "900",
    marginTop: 4,
  },
  heroStatDivider: {
    width: 1,
    height: 34,
    backgroundColor: "rgba(255,255,255,0.18)",
    marginHorizontal: 12,
  },

  panel: {
    backgroundColor: ui.card,
    borderRadius: 22,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: ui.border,
    shadowColor: ui.shadow,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.06,
    shadowRadius: 18,
    elevation: 2,
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  panelTitle: {
    color: ui.text,
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: -0.25,
  },
  panelFilter: {
    color: ui.textSoft,
    fontSize: 10,
    fontWeight: "800",
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 5,
    overflow: "hidden",
  },

  statusGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  statusMiniCardShell: {
    width: "48.5%",
    marginBottom: 10,
    borderRadius: 18,
    overflow: "hidden",
  },
  statusMiniCard: {
    borderRadius: 18,
    padding: 12,
    minHeight: 128,
    overflow: "hidden",
  },
  cardGlowOne: {
    position: "absolute",
    width: 86,
    height: 86,
    borderRadius: 86,
    backgroundColor: "rgba(255,255,255,0.18)",
    right: -34,
    top: -30,
  },
  cardGlowTwo: {
    position: "absolute",
    width: 56,
    height: 56,
    borderRadius: 56,
    backgroundColor: "rgba(255,255,255,0.10)",
    left: -22,
    bottom: -26,
  },
  statusMiniTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  statusValueWrap: {
    flex: 1,
    paddingRight: 8,
  },
  statusMiniValue: {
    color: "#FFFFFF",
    fontSize: 25,
    fontWeight: "900",
    letterSpacing: -0.8,
    lineHeight: 29,
  },
  statusMiniTitle: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "900",
    marginTop: 6,
  },
  statusMiniDesc: {
    color: "rgba(255,255,255,0.78)",
    fontSize: 9,
    fontWeight: "700",
    marginTop: 4,
    lineHeight: 12,
    minHeight: 22,
  },
  statusIcon: {
    width: 30,
    height: 30,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.20)",
    alignItems: "center",
    justifyContent: "center",
  },
  progressInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 9,
  },
  progressLabel: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 8.5,
    fontWeight: "800",
  },
  progressValue: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "900",
  },
  progressTrack: {
    height: 5,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.24)",
    marginTop: 5,
    overflow: "hidden",
  },
  progressFill: {
    height: 5,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
  },

  priorityList: {
    gap: 9,
  },
  priorityRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FAFCFF",
    paddingVertical: 12,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: "#E7EEF7",
    borderRadius: 16,
    overflow: "hidden",
  },
  priorityAccent: {
    position: "absolute",
    left: 0,
    top: 10,
    bottom: 10,
    width: 4,
    borderTopRightRadius: 99,
    borderBottomRightRadius: 99,
  },
  priorityIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  priorityTextWrap: {
    flex: 1,
    paddingRight: 8,
  },
  priorityTitle: {
    color: ui.text,
    fontSize: 12,
    fontWeight: "900",
  },
  priorityDesc: {
    color: ui.textSoft,
    fontSize: 10,
    fontWeight: "700",
    marginTop: 3,
    lineHeight: 14,
  },
  priorityRight: {
    alignItems: "flex-end",
  },
  priorityValue: {
    color: ui.text,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 5,
  },

  exceptionList: {
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  exceptionRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  exceptionIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  exceptionTextWrap: {
    flex: 1,
    paddingRight: 8,
  },
  exceptionTopRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  exceptionTitle: {
    flex: 1,
    color: ui.text,
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 16,
    paddingRight: 8,
  },
  exceptionTime: {
    color: ui.muted,
    fontSize: 9,
    fontWeight: "800",
  },
  exceptionMeta: {
    color: ui.textSoft,
    fontSize: 10,
    fontWeight: "700",
    marginTop: 4,
    lineHeight: 14,
  },
  rowLast: {
    borderBottomWidth: 0,
  },

  companionCard: {
    backgroundColor: ui.card,
    borderRadius: 20,
    padding: 15,
    borderWidth: 1,
    borderColor: ui.border,
    flexDirection: "row",
    alignItems: "center",
  },
  companionIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: "#E0F7FA",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  companionTextWrap: {
    flex: 1,
    paddingRight: 8,
  },
  companionTitle: {
    color: ui.text,
    fontSize: 13,
    fontWeight: "900",
  },
  companionDesc: {
    color: ui.textSoft,
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 15,
    marginTop: 3,
  },
});